# FreeRADIUS 3.x on Alpine (stable, production-ready)
# Note: FreeRADIUS 4 is still in alpha with limited package availability
# When v4 is stable, switch to Debian base with NetworkRADIUS packages
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
args:
  BUILD_FROM: ${build_from}
labels:
  io.hass.name: "FreeRADIUS Server"
  io.hass.description: "FreeRADIUS server with RadSec support for Meraki WPN Portal"
  io.hass.type: addon
  io.hass.version: "${version}"
  maintainer: "Josh Lipton <josh.lipton@outlook.com>"
  org.opencontainers.image.title: "FreeRADIUS Server"
  org.opencontainers.image.description: "FreeRADIUS server with RadSec and RADIUS over TLS support"
  org.opencontainers.image.source: "https://github.com/liptonj/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
