import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import ChangePSKForm from '../../src/components/ChangePSKForm'
import * as apiClient from '../../src/api/client'

vi.mock('../../src/api/client', () => ({
  changeUserPSK: vi.fn(),
  createQRToken: vi.fn(),
}))

describe('ChangePSKForm', () => {
  let queryClient: QueryClient
  const mockOnSuccess = vi.fn()

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  const renderComponent = (props = {}) => {
    return render(
      <QueryClientProvider client={queryClient}>
        <ChangePSKForm
          currentSSID="TestNetwork"
          onSuccess={mockOnSuccess}
          {...props}
        />
      </QueryClientProvider>
    )
  }

  it('renders PSK customizer', () => {
    renderComponent()
    
    expect(screen.getByText(/wifi password/i)).toBeInTheDocument()
    expect(screen.getByText(/auto-generate/i)).toBeInTheDocument()
  })

  it('shows warning about device disconnection', () => {
    renderComponent()
    
    expect(screen.getByText(/changing your wifi password will disconnect/i)).toBeInTheDocument()
  })

  it('submits with auto-generated PSK', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'AutoGenerated123',
      qr_code: 'data:image/png;base64,test',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    const submitButton = screen.getByText(/change wifi password/i)
    fireEvent.click(submitButton)
    
    await waitFor(() => {
      expect(apiClient.changeUserPSK).toHaveBeenCalledWith(undefined)
    })
  })

  it('submits with custom PSK', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'CustomPass123',
      qr_code: 'data:image/png;base64,test',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    // Switch to custom mode
    fireEvent.click(screen.getByText(/choose my own/i))
    
    // Enter custom password
    const input = screen.getByPlaceholderText(/enter your password/i)
    fireEvent.change(input, { target: { value: 'CustomPass123' } })
    
    // Submit
    const submitButton = screen.getByText(/change wifi password/i)
    fireEvent.click(submitButton)
    
    await waitFor(() => {
      expect(apiClient.changeUserPSK).toHaveBeenCalledWith('CustomPass123')
    })
  })

  it('shows success message with new QR code', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText(/wifi password updated/i)).toBeInTheDocument()
      expect(screen.getByText(/new wifi password/i)).toBeInTheDocument()
    })
  })

  it('displays new passphrase after successful change', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText('NewPassword123')).toBeInTheDocument()
    })
  })

  it('shows QR code actions after successful change', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText(/print/i)).toBeInTheDocument()
      expect(screen.getByText(/download/i)).toBeInTheDocument()
    })
  })

  it('calls onSuccess callback after successful change', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(mockOnSuccess).toHaveBeenCalled()
    })
  })

  it('shows error message when API call fails', async () => {
    vi.mocked(apiClient.changeUserPSK).mockRejectedValue(
      new Error('Failed to change password')
    )

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText(/failed to change password/i)).toBeInTheDocument()
    })
  })

  it('allows changing password again after successful change', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent()
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText(/change password again/i)).toBeInTheDocument()
    })
    
    fireEvent.click(screen.getByText(/change password again/i))
    
    expect(screen.getByText(/wifi password/i)).toBeInTheDocument()
  })

  it('disables submit button while loading', async () => {
    vi.mocked(apiClient.changeUserPSK).mockImplementation(
      () => new Promise(resolve => setTimeout(resolve, 100))
    )

    renderComponent()
    
    const submitButton = screen.getByText(/change wifi password/i)
    fireEvent.click(submitButton)
    
    expect(submitButton).toBeDisabled()
    expect(screen.getByText(/updating/i)).toBeInTheDocument()
  })

  it('uses current SSID in WiFi config string', async () => {
    const mockResponse = {
      success: true,
      new_passphrase: 'NewPassword123',
      qr_code: 'data:image/png;base64,newqr',
    }
    vi.mocked(apiClient.changeUserPSK).mockResolvedValue(mockResponse)

    renderComponent({ currentSSID: 'CustomNetwork' })
    
    fireEvent.click(screen.getByText(/change wifi password/i))
    
    await waitFor(() => {
      expect(screen.getByText('CustomNetwork')).toBeInTheDocument()
    })
  })
})
