build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22
  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22
args:
  BUILD_FROM: ${build_from}
labels:
  io.hass.name: "Meraki WPN Portal"
  io.hass.description: "Self-service WiFi registration portal for Cisco Meraki networks"
  io.hass.type: addon
  io.hass.version: "${version}"
  maintainer: "Josh Lipton <josh.lipton@outlook.com>"
  org.opencontainers.image.title: "Meraki WPN Portal"
  org.opencontainers.image.description: "Self-service WiFi registration portal with IPSK management"
  org.opencontainers.image.source: "https://github.com/liptonj/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
