build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
args:
  BUILD_FROM: ${build_from}
labels:
  io.hass.name: "Meraki WPN Portal"
  io.hass.description: "Self-service WiFi registration portal for Cisco Meraki networks"
  io.hass.type: addon
  io.hass.version: "${version}"
  maintainer: "Your Name <your.email@example.com>"
  org.opencontainers.image.title: "Meraki WPN Portal"
  org.opencontainers.image.description: "Self-service WiFi registration portal with IPSK management"
  org.opencontainers.image.source: "https://github.com/yourusername/meraki-wpn-portal"
  org.opencontainers.image.licenses: "MIT"
